name: flutter_embed_sdk
description: "ThoughtSpot's Flutter Embed SDK"
version: 0.0.2
repository: https://github.com/thoughtspot/flutter-embed-sdk

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mockito: ^5.4.4
  coverage: ^1.12.0

exclude:
  - scripts/

flutter:
