name: Flutter Tests and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-coverage:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"
          channel: "stable"

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov bc

      - name: Install Flutter Dependencies
        run: |
          flutter pub get
          flutter pub global activate build_runner
          flutter pub global activate mockito

      - name: Generate Mocks
        run: |
          chmod +x scripts/generate.sh
          dart run build_runner clean
          dart run build_runner build --delete-conflicting-outputs

      - name: Run Tests with Coverage
        run: |
          chmod +x scripts/test.sh
          ./scripts/test.sh --coverage

      - name: Upload Coverage Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html
